### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property.

### ISSUE THREAD

**Issue by princebillyGK** [ntkme/react-github-btn#9] opened 2020-11-29 12:14 UTC
I am working with "react-github-btn" and getting this error in my webstorm linter but the code works successfully. 

```
TS2607: JSX element class does not support attributes because it does not have a 'props' property.
TS2786: 'GitHubButton' cannot be used as a JSX component.
  Its instance type 'GitHubButton' is not a valid JSX element.
    Type 'GitHubButton' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.
```

**Comment by ntkme** [comment] 2020-11-30 05:24
I cannot reproduce your issue. I created a brand new project with `npx create-react-app my-app --template typescript` and added `react-github-btn`. No issue is reported by my tsserver linter.

Please try creating a new project with `npx create-react-app my-app --template typescript` and see if you can reproduce this issue with a brand new project with latest version of all dependencies.

**Comment by ntkme** [comment] 2021-08-20 22:28
This is likely an issue of webstorm. Closing.

**Closed by ntkme** 2021-08-20 22:28 UTC
