### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by afuscella** [ntkme/react-github-btn#11] opened 2021-03-26 18:16 UTC
Hey,
I'm facing a `SyntaxError: Cannot use import statement outside a module` when importing react-github-btn in my typescript project

```
import React, { PureComponent } from 'react'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.react-github-btn (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:3952:18)
    at __webpack_require__ (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:23:31)
    at Module../src/components/commons/GitHubButton/index.tsx (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:982:74)   
    at __webpack_require__ (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:23:31)
    at Module../src/components/commons/Cover/index.tsx (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:664:90)
    at __webpack_require__ (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:23:31)
    at Module../src/components/screen/HomeScreen/index.tsx (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:2712:83)     
    at __webpack_require__ (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:23:31)
    at Module../pages/index.tsx (C:\Users\I518644\git\afuscella\portfolio\.next\server\pages\index.js:105:87)
C:\Users\I518644\git\afuscella\portfolio\node_modules\react-github-btn\index.js:1
```

**Comment by ntkme** [comment] 2021-03-26 18:19
Duplicate of #10. Please refer to #10 for the solution.

**Closed by ntkme** 2021-03-26 18:19 UTC
